//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the following tool:
//        https://github.com/lithiumtoast/c2cs
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ReSharper disable All
//-------------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;

public static unsafe class refresh_image
{
    private const string LibraryName = "Refresh";

    [DllImport(LibraryName)]
    public static extern byte* Refresh_Image_Load([In] byte* filename, out int w, out int h, out int numChannels);

    [DllImport(LibraryName)]
    public static extern void Refresh_Image_Free(byte* mem);

    [DllImport(LibraryName)]
    public static extern void Refresh_Image_SavePNG([In] byte* filename, int w, int h, byte* data);
}
